// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Audio2TextProtobuffer.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Word;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Audio2TextProtobufferRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface Audio2TextProtobufferRoot : GPBRootObject
@end

#pragma mark - Text

typedef GPB_ENUM(Text_FieldNumber) {
  Text_FieldNumber_Vendor = 1,
  Text_FieldNumber_Version = 2,
  Text_FieldNumber_Seqnum = 3,
  Text_FieldNumber_Uid = 4,
  Text_FieldNumber_Flag = 5,
  Text_FieldNumber_Time = 6,
  Text_FieldNumber_Lang = 7,
  Text_FieldNumber_Starttime = 8,
  Text_FieldNumber_Offtime = 9,
  Text_FieldNumber_WordsArray = 10,
};

GPB_FINAL @interface Text : GPBMessage

@property(nonatomic, readwrite) int32_t vendor;

@property(nonatomic, readwrite) int32_t version;

@property(nonatomic, readwrite) int32_t seqnum;

@property(nonatomic, readwrite) int64_t uid;

@property(nonatomic, readwrite) int32_t flag;

@property(nonatomic, readwrite) int64_t time;

@property(nonatomic, readwrite) int32_t lang;

@property(nonatomic, readwrite) int32_t starttime;

@property(nonatomic, readwrite) int32_t offtime;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Word*> *wordsArray;
/** The number of items in @c wordsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger wordsArray_Count;

@end

#pragma mark - Word

typedef GPB_ENUM(Word_FieldNumber) {
  Word_FieldNumber_Text = 1,
  Word_FieldNumber_StartMs = 2,
  Word_FieldNumber_DurationMs = 3,
  Word_FieldNumber_IsFinal = 4,
  Word_FieldNumber_Confidence = 5,
};

GPB_FINAL @interface Word : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *text;

@property(nonatomic, readwrite) int32_t startMs;

@property(nonatomic, readwrite) int32_t durationMs;

@property(nonatomic, readwrite) BOOL isFinal;

@property(nonatomic, readwrite) double confidence;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
